///                     _       __ 
///  _ __  _ __ ___  __| | ___ / _|  
/// | '_ \| '__/ _ \/ _` |/ _ \ |_   predef - boost predef enhancements
/// | |_) | | |  __/ (_| |  __/  _|  ----------------------------------
/// | .__/|_|  \___|\__,_|\___|_|    https://github.com/q-ptr/predef
/// |_|                            
/// 
/// SPDX-FileCopyrightText: 2023 q-ptr
/// SPDX-License-Identifier: MIT

#pragma once


#include <boost/predef/architecture.h>


#if defined(BOOST_ARCH_ALPHA_AVAILABLE)
	#define QPTR_PREDEF_ARCHITECTURE_NAME   BOOST_ARCH_ALPHA_NAME
#elif defined(BOOST_ARCH_ARM_AVAILABLE)
	#define QPTR_PREDEF_ARCHITECTURE_NAME   BOOST_ARCH_ARM_NAME
#elif defined(BOOST_ARCH_BLACKFIN_AVAILABLE)
	#define QPTR_PREDEF_ARCHITECTURE_NAME   BOOST_ARCH_LACKFIN_NAME
#elif defined(BOOST_ARCH_CONVEX_AVAILABLE)
	#define QPTR_PREDEF_ARCHITECTURE_NAME   BOOST_ARCH_CONVEX_NAME
#elif defined(BOOST_ARCH_E2K_AVAILABLE)
	#define QPTR_PREDEF_ARCHITECTURE_NAME   BOOST_ARCH_E2K_NAME
#elif defined(BOOST_ARCH_IA64_AVAILABLE)
	#define QPTR_PREDEF_ARCHITECTURE_NAME   BOOST_ARCH_A64_NAME
#elif defined(BOOST_ARCH_M68K_AVAILABLE)
	#define QPTR_PREDEF_ARCHITECTURE_NAME   BOOST_ARCH_M68K_NAME
#elif defined(BOOST_ARCH_MIPS_AVAILABLE)
	#define QPTR_PREDEF_ARCHITECTURE_NAME   BOOST_ARCH_MIPS_NAME
#elif defined(BOOST_ARCH_PARISC_AVAILABLE)
	#define QPTR_PREDEF_ARCHITECTURE_NAME   BOOST_ARCH_PARISC_NAME
#elif defined(BOOST_ARCH_PPC_AVAILABLE)
	#define QPTR_PREDEF_ARCHITECTURE_NAME   BOOST_ARCH_PPC_NAME
#elif defined(BOOST_ARCH_PPC_64_AVAILABLE)
	#define QPTR_PREDEF_ARCHITECTURE_NAME   BOOST_ARCH_PPC_64_NAME
#elif defined(BOOST_ARCH_PTX_AVAILABLE)
	#define QPTR_PREDEF_ARCHITECTURE_NAME   BOOST_ARCH_TX_NAME
#elif defined(BOOST_ARCH_PYRAMID_AVAILABLE)
	#define QPTR_PREDEF_ARCHITECTURE_NAME   BOOST_ARCH_PYRAMID_NAME
#elif defined(BOOST_ARCH_RISCV_AVAILABLE)
	#define QPTR_PREDEF_ARCHITECTURE_NAME   BOOST_ARCH_RISCV_NAME
#elif defined(BOOST_ARCH_RS6000_AVAILABLE)
	#define QPTR_PREDEF_ARCHITECTURE_NAME   BOOST_ARCH_RS6000__NAME
#elif defined(BOOST_ARCH_SPARC_AVAILABLE)
	#define QPTR_PREDEF_ARCHITECTURE_NAME   BOOST_ARCH_SPARC_NAME
#elif defined(BOOST_ARCH_SH_AVAILABLE)
	#define QPTR_PREDEF_ARCHITECTURE_NAME   BOOST_ARCHSH__NAME
#elif defined(BOOST_ARCH_SYS370_AVAILABLE)
	#define QPTR_PREDEF_ARCHITECTURE_NAME   BOOST_ARCH_SYS370_NAME
#elif defined(BOOST_ARCH_SYS390_AVAILABLE)
	#define QPTR_PREDEF_ARCHITECTURE_NAME   BOOST_ARCH_SYS390_NAME
#elif defined(BOOST_ARCH_Z_AVAILABLE)
	#define QPTR_PREDEF_ARCHITECTURE_NAME   BOOST_ARCH_Z_NAME
#elif defined(BOOST_ARCH_X86_32_AVAILABLE)
	#define QPTR_PREDEF_ARCHITECTURE_NAME   BOOST_ARCH_X86_32_NAME
#elif  defined(BOOST_ARCH_X86_64_AVAILABLE)
	#define QPTR_PREDEF_ARCHITECTURE_NAME   BOOST_ARCH_X86_64_NAME
#else
	#define QPTR_PREDEF_ARCHITECTURE_NAME   "<unknown-compiler>"
#endif
