///                     _       __ 
///  _ __  _ __ ___  __| | ___ / _|  
/// | '_ \| '__/ _ \/ _` |/ _ \ |_   predef - boost predef enhancements
/// | |_) | | |  __/ (_| |  __/  _|  ----------------------------------
/// | .__/|_|  \___|\__,_|\___|_|    https://github.com/q-ptr/predef
/// |_|                            
/// 
/// SPDX-FileCopyrightText: 2023 q-ptr
/// SPDX-License-Identifier: MIT

#pragma once


#include <boost/predef/compiler.h>


#if defined(BOOST_COMP_BORLAND_AVAILABLE)
	#define QPTR_PREDEF_COMPILER_NAME   BOOST_COMP_BORLAND_NAME
#elif defined(BOOST_COMP_CLANG_AVAILABLE)
	#define QPTR_PREDEF_COMPILER_NAME   BOOST_COMP_CLANG_NAME
#elif defined(BOOST_COMP_COMO_AVAILABLE)
	#define QPTR_PREDEF_COMPILER_NAME   BOOST_COMP_COMO_NAME
#elif defined(BOOST_COMP_DEC_AVAILABLE)
	#define QPTR_PREDEF_COMPILER_NAME   BOOST_COMP_DEC_NAME
#elif defined(BOOST_COMP_DIAB_AVAILABLE)
	#define QPTR_PREDEF_COMPILER_NAME   BOOST_COMP_DIAB_NAME
#elif defined(BOOST_COMP_DMC_AVAILABLE)
	#define QPTR_PREDEF_COMPILER_NAME   BOOST_COMP_DMC_NAME
#elif defined(BOOST_COMP_SYSC_AVAILABLE)
	#define QPTR_PREDEF_COMPILER_NAME   BOOST_COMP_SYSC_NAME
#elif defined(BOOST_COMP_EDG_AVAILABLE)
	#define QPTR_PREDEF_COMPILER_NAME   BOOST_COMP_EDG_NAME
#elif defined(BOOST_COMP_PATH_AVAILABLE)
	#define QPTR_PREDEF_COMPILER_NAME   BOOST_COMP_PATH_NAME
#elif defined(BOOST_COMP_GNUC_AVAILABLE)
	#define QPTR_PREDEF_COMPILER_NAME   BOOST_COMP_GNUC_NAME
#elif defined(BOOST_COMP_GCCXML_AVAILABLE)
	#define QPTR_PREDEF_COMPILER_NAME   BOOST_COMP_GCCXML_NAME
#elif defined(BOOST_COMP_GHS_AVAILABLE)
	#define QPTR_PREDEF_COMPILER_NAME   BOOST_COMP_GHS_NAME
#elif defined(BOOST_COMP_HPACC_AVAILABLE)
	#define QPTR_PREDEF_COMPILER_NAME   BOOST_COMP_HPACC_NAME
#elif defined(BOOST_COMP_IAR_AVAILABLE)
	#define QPTR_PREDEF_COMPILER_NAME   BOOST_COMP_IAR_NAME
#elif defined(BOOST_COMP_IBM_AVAILABLE)
	#define QPTR_PREDEF_COMPILER_NAME   BOOST_COMP_IBM_NAME
#elif defined(BOOST_COMP_INTEL_AVAILABLE)
	#define QPTR_PREDEF_COMPILER_NAME   BOOST_COMP_INTEL_NAME
#elif defined(BOOST_COMP_KCC_AVAILABLE)
	#define QPTR_PREDEF_COMPILER_NAME   BOOST_COMP_KCC_NAME
#elif defined(BOOST_COMP_LLVM_AVAILABLE)
	#define QPTR_PREDEF_COMPILER_NAME   BOOST_COMP_LLVM_NAME
#elif defined(BOOST_COMP_HIGHC_AVAILABLE)
	#define QPTR_PREDEF_COMPILER_NAME   BOOST_COMP_HIGHC_NAME
#elif defined(BOOST_COMP_MWERKS_AVAILABLE)
	#define QPTR_PREDEF_COMPILER_NAME   BOOST_COMP_MWERKS_NAME
#elif defined(BOOST_COMP_MRI_AVAILABLE)
	#define QPTR_PREDEF_COMPILER_NAME   BOOST_COMP_MRI_NAME
#elif defined(BOOST_COMP_MPW_AVAILABLE)
	#define QPTR_PREDEF_COMPILER_NAME   BOOST_COMP_MPW_NAME
#elif defined(BOOST_COMP_NVCC_AVAILABLE)
	#define QPTR_PREDEF_COMPILER_NAME   BOOST_COMP_NVCC_NAME
#elif defined(BOOST_COMP_PALM_AVAILABLE)
	#define QPTR_PREDEF_COMPILER_NAME   BOOST_COMP_PALM_NAME
#elif defined(BOOST_COMP_PGI_AVAILABLE)
	#define QPTR_PREDEF_COMPILER_NAME   BOOST_COMP_PGI_NAME
#elif defined(BOOST_COMP_SGI_AVAILABLE)
	#define QPTR_PREDEF_COMPILER_NAME   BOOST_COMP_SGI_NAME
#elif defined(BOOST_COMP_SUNPRO_AVAILABLE)
	#define QPTR_PREDEF_COMPILER_NAME   BOOST_COMP_SUNPRO_NAME
#elif defined(BOOST_COMP_TENDRA_AVAILABLE)
	#define QPTR_PREDEF_COMPILER_NAME   BOOST_COMP_TENDRA_NAME
#elif defined(BOOST_COMP_MSVC_AVAILABLE)
	#define QPTR_PREDEF_COMPILER_NAME   BOOST_COMP_MSVC_NAME
#elif defined(BOOST_COMP_WATCOM_AVAILABLE)
	#define QPTR_PREDEF_COMPILER_NAME   BOOST_COMP_WATCOM_NAME
#else
	#define QPTR_PREDEF_COMPILER_NAME   "<unknown-compiler>"
#endif
